### PR TITLE
First draft of code style

### PR DESCRIPTION
**Pull request by schmidsi**
I just had some inspiration for our code style guide and wrote it down. Naturally, they come from my Javascript perspective, but I think the general ones should apply to solidity and other frameworks/languages also.  

I'm open for suggestions and discussions.

### CODE REVIEW

**Comment by retotrinkler** [comment]
v nice @schmidsi !

@travs, @GauthamN we should eventually do something similar for solidity style of protocol contracts

**Comment by retotrinkler** [comment]
prob would add **Code is consistency** in Preamble

**Comment by retotrinkler** [comment]
we prob should mention and require these under #Git section for our repos as well
- PULL_REQUEST_TEMPLATE
- ISSUE_TEMPLATE
- CONTRIBUTING
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by schmidsi** [comment]
I'd like to harmonise code style across Solidity and Javascript as much as possible, where Solidity can take the lead. That said, I don't know how much standardised Solidity code styles are at the moment. So I'm looking forward to your inputs.

**Comment by retotrinkler** [comment]
harmonise code style across languages sounds like a good idea.

there is an official style guide http://solidity.readthedocs.io/en/develop/style-guide.html

we modified by 

- using `///` [natspecs comments](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format)
- using _Design by contract_ style `DBC.sol` meaning no `modifier` but `PRE, POST, INVARIANT CONDITIONS`
- using _SafeMath` library
- and a specific ordering

```
pragma solidity ^0.4.17;

import './dependencies/DBC.sol';
import './libraries/safeMath.sol';

/// @title Title of contract
/// @author Melonport AG <team@melonport.com>
contract ContractName is DBC {
    using safeMath for uint;

    // TYPES

    // FIELDS

    // Constant fields
    // Constructor fields
    // Methods fields

    // PRE, POST, INVARIANT CONDITIONS

    // CONSTANT METHODS

    // NON-CONSTANT METHODS
}

```

**Comment by retotrinkler** [comment]
a function should look like

```

    /// @notice Use only for public or external functions - intended for user
    /// @dev Description of function - intended for developers
    /// @param inputParam Description of inputParam
    /// @return returnValue Description of returnValue
    function functionName(
        type inputValue
    )
        functionVisibility // eg _public!
        pre_cond(preCondition()) // preCondition as defined in PRE, POST, INVARIANT section
        post_cond(postCondition()) // postCondition as defined in PRE, POST, INVARIANT section
        returns (type returnValue)
    {
        ...
    }
```

**Comment by schmidsi** [comment]
Closing this since WIP is here: https://hackmd.io/41CRHAJXRu2Ir2UQG4Ba0Q#

**Pull request closed without merging**
